language: rust
dist: xenial
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo apt-get update -qq
  - sudo apt install libssh2-1-dev python3-pip docker-compose -y
  - python3 --version
  - sudo -H python3 -m pip install --upgrade pip setuptools
  - sudo -H python3 -m pip install -r requirements.txt
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - docker-compose up -d gerrit
  - set -o pipefail; behave -v -D gerrit_start_timeout=60 | cat
