language: rust
dist: xenial
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get update -qq
  - sudo apt install libssh2-1-dev python3.6 docker-compose -y
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python3.6 get-pip.py
  - python3.6 -m pip install --user -r requirements.txt
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - docker-compose up -d gerrit
  - set -o pipefail; python3.6 -m behave -v -D gerrit_start_timeout=60 -D gerritbot_message_timeout=1 | cat
