language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libdbus-1-dev libssh2-1-dev -y
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
