[package]
name = "gerritbot"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]

[dependencies]
futures = "0.1.x"
hyper = "0.10.x"
hyper-native-tls = "*"
iron = "0.5.x"
router = "0.5.x"
serde = "1.0.x"
serde_derive = "1.0.x"
serde_json = "1.0.x"
ssh2 = "0.3"