gerrit:
  hostname: localhost
  port: 29418
  username: rmp-bot
  priv_key_path: testing/id_rsa

spark:
  uri: https://api.ciscospark.com/v1
  bot_token: ""
  mode: 
    Sqs:
      uri: ""
      region: "us-east-1"
  
bot:
  msg_expiration: 4
  msg_capacity: 100