gerrit:
  hostname: localhost
  port: 29418
  username: admin
  priv_key_path: testing/id_rsa

spark:
  api_uri: https://api.ciscospark.com/v1
  bot_token: ""
  # optional, add a webhook URL is you want to register it automatically on Cisco Spark
  # webhook_url: "https://endpoint.example.org"
  mode: 
    Direct:
      endpoint: "localhost:8888"

  
bot:
  msg_expiration: 4
  msg_capacity: 100