version: "3.4"

services:
  gerrit:
    build:
      context: testing
      dockerfile: Dockerfile.gerrit
    ports:
      - 8080:8080
      - 29418:29418
    volumes:
      - ./.git:/root/src.git:ro
      - ./testing/data/src:/root/data/src
    environment:
      - USER_NAME=gerrit
      - USER_EMAIL=gerrit@localhost
      - WEBURL=http://localhost:8080
      - AUTH_TYPE=DEVELOPMENT_BECOME_ANY_ACCOUNT

  bot:
    build:
      context: testing
      dockerfile: Dockerfile.bot
    volumes:
      - .:/src:ro
      - ./testing/data/target:/src/target
    depends_on:
      - gerrit
