[package]
name = "gerritbot-spark"
version = "0.7.0"
authors = ["boxdot <d@zerovolt.org>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
docopt = "1.0"
futures = "0.1"
hyper = "0.10"
hyper-native-tls = "0.2"
iron = "0.6"
lazy_static = "1.3"
log = "0.4"
notify-rust = "3"
regex = "1.1"
router = "0.6"
rusoto_core = "0.36"
rusoto_sqs = "0.36"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-core = "0.1"

[dev-dependencies]
structopt = "0.2"
stderrlog = "0.4"
toml = "0.4"